### ISSUE TITLE
Separate js files in the example

### ISSUE THREAD

**Issue by pavelnikolov** [googollee/go-engine.io#11]
In the example's asset folder there is an index.js file. It contains engine.io, smoothie chart and app code. It would be better if the code is stored in separate files. This way it will be easier for everyone to understand the example and get the minimal code needed to build an application. It would also help others to debug the code and find problems.

**Comment by googollee** [comment]
Hi, I'm working on refactoring whole go-socket.io, targeting on more robust implement and less memory footprint.

I just finished the work of go-engine.io, which is `v1.4` branch. As I remain old version on `1.0` branch and `master` branch, I recommend to get new code through `gopkg.in/googollee/go-engine.io.v1`.

As your interesting, could you help to review the code in `v1.4` branch? It's not compatible with old code, but API doesn't change to much. It should be easy to be understood.

I will keep this issue a while before finishing go-socket.io.
