### ISSUE TITLE
once MaxConnection is reached, server can never recover

### ISSUE THREAD

**Issue by armhold** [googollee/go-engine.io#27]
Today is only my 3rd day with Golang, so please excuse me if I have made a newbie mistake. But I believe that there's a bug in detecting MaxConnections. If I understand correctly, `currentConnection` is really a count of the number of connected sessions (`connectionCount` might be a better name?)

So on [server.go line 124](https://github.com/googollee/go-engine.io/blob/master/server.go#L124), `s.currentConnection` is incremented, and then returns an error to the client. This variable should be decremented prior to the return (or better yet, never incremented in the first place). 

Explanation: if the server is currently maxed out, and (for example) 5 more clients attempt to join, this will push the server 5 over the limit. And so clients will be locked out until at least 5 current clients close. If you have a busy server, it might never recover. I discovered this during load testing.

The `atomic.AddInt32` call implies some kind of threading issue; a cleaner solution might be to augment the Sessions interface to also have a `Count()`, which would then be responsible for the thread safety as well. Since `Get/Set/Remove` all just delegate to the `sessions` map, the default implementation could then simply return `len(sessions)`.

**Comment by googollee** [comment]
Hi, I'm working on refactoring whole go-socket.io, targeting on more robust implement and less memory footprint.

I just finished the work of go-engine.io, which is `v1.4` branch. As I remain old version on `1.0` branch and `master` branch, I recommend to get new code through `gopkg.in/googollee/go-engine.io.v1`.

As your interesting, could you help to review the code in `v1.4` branch? It's not compatible with old code, but API doesn't change to much. It should be easy to be understood.

I will keep this issue a while before finishing go-socket.io.
