### ISSUE TITLE
Stall in upgrade (race condition)

### ISSUE THREAD

**Issue by Adrien-P** [googollee/go-engine.io#33]
I'm experiencing a race condition on upgrading (polling -> websocket)
Related topics: https://github.com/socketio/engine.io-client/issues/18 and https://github.com/socketio/engine.io/issues/174

The sequence of the problem is the following:
- engine.io-client (javascript) sends a ping probe (`2probe`) on the websocket connection just created
- engine.io server (javascript or go-engine.io) responds with two packets: a pong probe (`3probe`) on the websocket connection and a `noop` packet on the polling connection. The goal of the `noop` is to close the polling connection
- When engine.io-client receives the `3probe` it "pauses" the polling connection. Basically, as soon as the latest ongoing polling is over (a packet has been received from the server, for example a `noop`) the "pause" is finished and the transport is set to websocket. This is when the client sends a 'upgrade' to the server and so the upgrade is finished. 

Until this "pause" is finished, the 'upgrade' is not sent and so the connection is still seen as 'upgrading' on the server and so the server refuses to send any message to this client ('upgrading').
The problem can arise in the second step of the sequence above: if the `noop` arrives before the `3probe` then it does not close the latest polling connection (the client has not started "pausing" yet). So a new polling connection will be opened and the client will wait the next packet to finish the pausing. Usually it is a "ping" packet sent from the server and it can take a while (it depends on the ping interval set in the configuration). Clearly, in this data race condition the `noop` packet is not filling its role (it's closing the latest polling **before** the pause instead of **after**).
Here is the handler of the `3probe` in the engine.io-client: https://github.com/socketio/engine.io-client/blob/master/lib/socket.js#L294

The javascript engine.io server has a workaround for this problem by sending multiple `noop` to "ensure a fast upgrade" (https://github.com/socketio/engine.io/blob/master/lib/socket.js#L215)

In my opinion this is a workaround and the problem is sitting in engine.io-client in the way it does the "pause" process.
However, because the fix has been made in the server part I suggest that we do the same here to solve this issue.
I can think about a similar workaround that would basically replace this bit: https://github.com/googollee/go-engine.io/blob/master/server_conn.go#L213  by a for loop that would only stop when `c.getUpgrade()==nil`. It would effectively send `noop` packets until the upgrade is over.
I've tested this workaround locally, it works and usually it does not send more than two `noop` packets.
I can do a pull request if this solution looks good to you

**Comment by bryanpaluch** [comment]
@Adrien-P can you post your pull request here? I'm hitting the same issue.

**Comment by bryanpaluch** [comment]
Found your fork. This works great, good find.

**Comment by simcap** [comment]
@bryanpaluch in the case you will still use future version of our fork note that we just pushed force after a necessary rebase. So do a clean git clone or `go get -u ... ` I guess

**Comment by nkovacs** [comment]
@Adrien-P your fix has a data race, run the tests with `go test -race` in the root of the project.

**Comment by Adrien-P** [comment]
Yes @nkovacs, I noticed it but forgot to report it here. My apologies.
We faced a lot of issues with go-engine.io (in production) and we decided to move away from it.

**Comment by googollee** [comment]
Hi, I'm working on refactoring whole go-socket.io, targeting on more robust implement and less memory footprint.

I just finished the work of go-engine.io, which is `v1.4` branch. As I remain old version on `1.0` branch and `master` branch, I recommend to get new code through `gopkg.in/googollee/go-engine.io.v1`.

As your interesting, could you help to review the code in `v1.4` branch? It's not compatible with old code, but API doesn't change to much. It should be easy to be understood.

I will keep this issue a while before finishing go-socket.io.

**Comment by jroper** [comment]
The analysis in this issue is great, I found the same problem when implementing a socket.io server for Play, I completely agree the "fix" in the javascript engine.io server is not a fix at all. This issue saved me a lot of time in coming up with a work around.

IMO, a proper fix would be to change the protocol to make upgrade a two step process - first the client tells the server it intends to upgrade, then it pauses the polling transport if there is an outstanding poll, then when the server receives the intent to upgrade, it starts responding to any existing and new polls with noop. Then when the client receives an answer to its outstanding poll, it can tell the server to complete the upgrade, at which point the server can start sending messages to the WebSocket.
