### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by Adrien-P** [googollee/go-engine.io#34]
In production we've got this error:
`panic: close of closed channel`
It created a lot of unstability.
The channel at hand is here:
https://github.com/googollee/go-engine.io/blob/master/server_conn.go#L255

I don't have ideas about how to solve this problem.
A bit of context:
We have clients doing polling then upgrade to websocket.
Some can fail the websocket upgrade (firewall restrictions for example)

Any help would be appreciated

**Comment by nkovacs** [comment]
Do you have a stack trace? I wasn't able to reproduce this, but I looked at the code, and I think the only place this can happen is when the connection is closed while it is upgrading.

**Comment by googollee** [comment]
Hi, I'm working on refactoring whole go-socket.io, targeting on more robust implement and less memory footprint.

I just finished the work of go-engine.io, which is `v1.4` branch. As I remain old version on `1.0` branch and `master` branch, I recommend to get new code through `gopkg.in/googollee/go-engine.io.v1`.

As your interesting, could you help to review the code in `v1.4` branch? It's not compatible with old code, but API doesn't change to much. It should be easy to be understood.

I will keep this issue a while before finishing go-socket.io.

**Comment by richmonkey** [comment]
goroutine 1472914 [running]:
panic(0x81b820, 0xc825044a90)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/googollee/go-engine.io/polling.(*Polling).Close(0xc825533140, 0x0, 0x0)
        /goproject/src/github.com/googollee/go-engine.io/polling/server.go:63 +0x5e
github.com/googollee/go-engine%2eio.(*serverConn).Close(0xc8262f8410, 0x0, 0x0)
        /goproject/src/github.com/googollee/go-engine.io/server_conn.go:174 +0x217
github.com/googollee/go-engine%2eio.(*serverConn).pingLoop(0xc8262f8410)
        /goproject/src/github.com/googollee/go-engine.io/server_conn.go:376 +0x416
created by github.com/googollee/go-engine%2eio.newServerConn
        /goproject/src/github.com/googollee/go-engine.io/server_conn.go:110 +0x58e

**Comment by richmonkey** [comment]
Close the serverConn on a goroutine, and pingLoop goroutine close the serverConn on the same time,  the panic occurs.

**Comment by zs1379** [comment]
panic: close of closed channel
I got a same panic on the production, does anyone already fix that?

**Comment by mattli001** [comment]
@zs1379 may be you could try this : https://github.com/azhao1981/go-engine.io/commit/4f280f1c42e1295c571117367f2a33cbaae65714
It add panic recover.
