### ISSUE TITLE
http: response.WriteHeader on hijacked connection

### ISSUE THREAD

**Issue by mceldeen** [googollee/go-engine.io#35]
When going straight to a websocket connection (and skipping the HTTP long polling handshake), the server logs `http: response.WriteHeader on hijacked connection`. This is not a huge problem but it is unnecessary. The reason for this is because the [`ServeHTTP`](https://github.com/googollee/go-engine.io/blob/master/websocket/server.go#L35) method is never expected to be called. When the client's first request is for a websocket, it does get called. Perhaps, we can detect this and make it a noop (because the connection has already been hijacked so we don't need to do anything).

**Comment by googollee** [comment]
Hi, I'm working on refactoring whole go-socket.io, targeting on more robust implement and less memory footprint.

I just finished the work of go-engine.io, which is `v1.4` branch. As I remain old version on `1.0` branch and `master` branch, I recommend to get new code through `gopkg.in/googollee/go-engine.io.v1`.

As your interesting, could you help to review the code in `v1.4` branch? It's not compatible with old code, but API doesn't change to much. It should be easy to be understood.

I will keep this issue a while before finishing go-socket.io.
