### ISSUE TITLE
Polling p.sendChan may cause a great delay (20+ secs)

### ISSUE THREAD

**Issue by icebobofly** [googollee/go-engine.io#39]
https://github.com/googollee/go-engine.io/blob/master/polling/server.go#L117

**Comment by googollee** [comment]
Hi, I'm working on refactoring whole go-socket.io, targeting on more robust implement and less memory footprint.

I just finished the work of go-engine.io, which is `v1.4` branch. As I remain old version on `1.0` branch and `master` branch, I recommend to get new code through `gopkg.in/googollee/go-engine.io.v1`.

As your interesting, could you help to review the code in `v1.4` branch? It's not compatible with old code, but API doesn't change to much. It should be easy to be understood.

I will keep this issue a while before finishing go-socket.io.
