### ISSUE TITLE
Panic on send to pingChan in OnPacket

### ISSUE THREAD

**Issue by navneetk** [googollee/go-engine.io#40]
I am using this version a66cf68

`case parser.PONG:
        c.pingChan <- true`

> goroutine 2934740 [running]:
>  panic(0xaffb20, 0xc823eb7ca0)
>      /home/navneet/go/go1.6.2/src/runtime/panic.go:481 +0x3e6
>  github.com/googollee/go-engine%2eio.(_serverConn).OnPacket(0xc821588f70, 0xc823c2de80)
>      /home/navneet/repo/pubsub/_vendor/src/github.com/googollee/go-engine.io/server_conn.go:228 +0x44c
>  github.com/googollee/go-engine.io/websocket.(_Server).serveHTTP(0xc82486d820, 0x7ff3132310c8, 0xc8213e80d0, 0xc8223a4c40)
>      /home/navneet/repo/pubsub/_vendor/src/github.com/googollee/go-engine.io/websocket/server.go:77 +0x196
>  created by github.com/googollee/go-engine.io/websocket.NewServer
>      /home/navneet/repo/pubsub/_vendor/src/github.com/googollee/go-engine.io/websocket/server.go:29 +0x16d

**Comment by googollee** [comment]
Hi, I'm working on refactoring whole go-socket.io, targeting on more robust implement and less memory footprint.

I just finished the work of go-engine.io, which is `v1.4` branch. As I remain old version on `1.0` branch and `master` branch, I recommend to get new code through `gopkg.in/googollee/go-engine.io.v1`.

As your interesting, could you help to review the code in `v1.4` branch? It's not compatible with old code, but API doesn't change to much. It should be easy to be understood.

I will keep this issue a while before finishing go-socket.io.

**Comment by nikhilmahesh** [comment]
I got something similar in my google cloud logs :


23:23:42.000
/go/src/github.com/googollee/go-engine.io/websocket/server.go:29 +0x16d
{
 textPayload: "	/go/src/github.com/googollee/go-engine.io/websocket/server.go:29 +0x16d
"   
 insertId: "46fh2kg1nlepsk"   
 resource: {…}   
 timestamp: "2017-01-09T17:53:42Z"   
 severity: "ERROR"   
 labels: {…}   
 logName: "projects/pret-saggarwal/logs/stress-chat"   
}
23:23:42.000
created by github.com/googollee/go-engine.io/websocket.NewServer
23:23:42.000
/go/src/github.com/googollee/go-engine.io/websocket/server.go:77 +0x196
23:23:42.000
github.com/googollee/go-engine.io/websocket.(*Server).serveHTTP(0xc855a19240, 0x7f59fac60170, 0xc852a33520, 0xc83eeb88c0)
23:23:42.000
/go/src/github.com/googollee/go-engine.io/server_conn.go:226 +0x488
23:23:42.000
github.com/googollee/go-engine%2eio.(*serverConn).OnPacket(0xc84131c8f0, 0xc854952100)
23:23:42.000
/usr/local/go/src/runtime/panic.go:481 +0x3e6
23:23:42.000
panic(0x7f04e0, 0xc84f27dd90)
23:23:42.000
goroutine 118198 [running]:
23:23:42.000
23:23:42.000
panic: send on closed channel
23:23:42.000
2017/01/09 17:53:42 Total Connected to Server 1483981243538819558 : 12054

This happens anytime after 5000 simultaneous connections.
