### ISSUE TITLE
Server.ServeHTTP:  when newServerConn failed should decrease connection count 

### ISSUE THREAD

**Issue by aiden0z** [googollee/go-engine.io#44]
refer https://github.com/googollee/go-engine.io/blob/master/server.go#L134-L148

```
        n := atomic.AddInt32(&s.currentConnection, 1)
        if int(n) > s.config.MaxConnection {
            atomic.AddInt32(&s.currentConnection, -1)
            http.Error(w, "too many connections", http.StatusServiceUnavailable)
            return
        }

        sid = s.config.NewId(r)

        var err error
        conn, err = newServerConn(sid, w, r, s)
        if err != nil {
            // should decrease the connection count here
            http.Error(w, err.Error(), http.StatusBadRequest)
            return
        }

```

Description:

When there is only websocket transport but client using polling transport  connect to the server, the server will increase the connection count, but no chance to decrease it because of the server conn creation failed.

**Comment by googollee** [comment]
Hi, I'm working on refactoring whole go-socket.io, targeting on more robust implement and less memory footprint.

I just finished the work of go-engine.io, which is `v1.4` branch. As I remain old version on `1.0` branch and `master` branch, I recommend to get new code through `gopkg.in/googollee/go-engine.io.v1`.

As your interesting, could you help to review the code in `v1.4` branch? It's not compatible with old code, but API doesn't change to much. It should be easy to be understood.

I will keep this issue a while before finishing go-socket.io.
