### ISSUE TITLE
v1.4 现在是否已完工，能否线上使用，谢谢

### ISSUE THREAD

**Issue by ruandao** [googollee/go-engine.io#48]
线上用的话，有哪些风险。。。？
master上的代码，一直在崩溃。。。我已崩溃

**Comment by pangdahua** [comment]
v1.4 功能还十分简陋， 刚试了下在polling 下崩溃了。

**Comment by erkie** [comment]
If you have specific bugs or issues please post a stracktrace and if possible steps to reproduce.
