### ISSUE TITLE
Fix check origin gorilla web socket

### ISSUE THREAD

**Issue by w0dm4n** [googollee/go-engine.io#64]
Hello,
You need to add 

> CheckOrigin: func(r *http.Request) bool {
> 			return true
> 		},

to transport/websocket/transport.go. It cause 403 Forbidden when using CORS to allow external origins. on gorilla websocket:

> if !checkOrigin(r) {
> 		return u.returnError(w, r, http.StatusForbidden, "websocket: request origin not allowed by Upgrader.CheckOrigin")
> 	}
in the server.go

So it's blocking every request

**Comment by erkie** [comment]
You need to wrap your server in a custom `ServeHTTP(w http.ResponseWriter, r *http.Request)` method.

**Comment by euclid1990** [comment]
@erkie Can you explain or give me some sample code ? I have faced this issue. 
```
type SocketIoServer struct {
	*socketio.Server
}

func NewSocketServer() (*SocketIoServer, error) {
	io, err := socketio.NewServer(nil)
	if err != nil {
		return nil, err
	}
	return &SocketIoServer{io}, nil
}

func (s *SocketIoServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	log.Println(r.Header)
	OriginList := r.Header["Origin"]
	Origin := ""
	if len(OriginList) > 0 {
		Origin = OriginList[0]
	}
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Credentials", "true")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, accept, origin, Cache-Control, X-Requested-With")
	w.Header().Set("Access-Control-Allow-Methods", "POST, OPTIONS, GET, PUT")
	s.Server.ServeHTTP(w, r)
}
```
I have try to wrap ServeHTTP, but it have been not working correctly. It return this error while I call websocket from another domain:
![image](https://user-images.githubusercontent.com/5584709/58465068-21c6d380-8161-11e9-857d-5e86b69ff68d.png)
Thank you

**Comment by BuiChiBach** [comment]
@euclid1990 have you fix it ? I have the same issue !

**Comment by erkie** [comment]
@BuiChiBach can you perhaps include a working sample project to reproduce this?

**Comment by BuiChiBach** [comment]
I tried to integrate Gin & googollee/go-socket.io , this is main function in Server 
`func main() {
	r := setupRouter()

	server, err := socketio.NewServer(nil)
	if err != nil {
		fmt.Println(err)
	}
	server.OnConnect("/", func(s socketio.Conn) error {
		s.SetContext("")
		fmt.Println("connected:", s.ID())
		s.Emit("hello", "chao front-end")
		fmt.Println("co nguoi connect")
		return nil
	})
	server.OnEvent("/", "notice", func(s socketio.Conn, msg string) {
		fmt.Println("notice:", msg)
		s.Emit("reply", "have "+msg)
	})
	server.OnEvent("/chat", "msg", func(s socketio.Conn, msg string) string {
		s.SetContext(msg)
		return "recv " + msg
	})
	server.OnEvent("/", "bye", func(s socketio.Conn) string {
		last := s.Context().(string)
		s.Emit("bye", last)
		s.Close()
		return last
	})
	server.OnError("/", func(e error) {
		fmt.Println("meet error:", e)
	})
	server.OnDisconnect("/", func(s socketio.Conn, msg string) {
		fmt.Println("closed", msg)
	})

	// var c *gin.Context
	go server.Serve()
	defer server.Close()

	r.GET("/socket.io/", gin.WrapH(server))
	r.POST("/socket.io/", gin.WrapH(server))

	r.Run(":9090")
}`

and in Client side , I use socketio-client to handshake with server 
`import React, { Component } from 'react';
import './App.css';
import io from 'socket.io-client';

// const ws = new WebSocket("ws://localhost:8080/ws");

class App extends Component {


  state = {
    content: ""
  }

  clickme = () => {

  }

  componentDidMount() {
    const socket = io('http://localhost:9090/socket.io');
    console.log(socket);
    socket.emit("notice", "hahaha");
    socket.on("reply", data => {
      console.log(data);
    })

    socket.on("hello", data => {
      console.log(data);
    })

  }


  render() {
    return (
      <div className="App">
        <button onClick={this.clickme}>Click me oh yeah</button>
      </div>
    );
  }
}

export default App;`

and then it return this error 
![Annotation 2019-08-26 162637](https://user-images.githubusercontent.com/44353566/63680622-498c0d00-c81e-11e9-92b3-02f6589cda97.png)

**Comment by exapsy** [comment]
> You need to wrap your server in a custom `ServeHTTP(w http.ResponseWriter, r *http.Request)` method.

I'm not sure what you meant there what how was that supposed to solve the issue. But the proposal itself alone isn't helpful at all :P Nothing special happens if you wrap it in a "custom ServeHTTP" method. :)

I think we have to put a way in engineio.Options to put a custom transport checkOrigin method from the user's standpoint.
