### ISSUE TITLE
PingChan can be closed outside of the pingLocker

### ISSUE THREAD

**Issue by steveoc64** [googollee/go-engine.io#68]
Can I get some code review on this PR on our branch of go-engine.io please.  Need some more eyes on it.

Got an issue where it actually tried to write to pingChan, when pingChan is closed.  Pretty rare - we have hit this at least once, in what would be a very large number of connections over that period.

This is a bit odd, because the pingLocker looks like it will prevent this.  However, there is a tiny slice of time where this is not true.  This lines up well with the low error rate, and my hypothesis about why it died when it did.

https://github.com/divisionone/go-engine.io/pull/4/files

**Comment by erkie** [comment]
Seems that your fork is based on 0.9 which has been archived. The current master branch (aka 1.4) works differently. I would recommend upgrading and then your error will probably disappear.

**Comment by steveoc64** [comment]
no probs.  We are still using the ancient version in prod.  Its pretty stable considering the load its under, but occassionally it goes boom.

Will bring it up next week that we really should move on and get up to date with 1.4.

Thx
