### ISSUE TITLE
read & write different goroutines concurrent

### ISSUE THREAD

**Issue by richmonkey** [googollee/go-engine.io#69]
latest version can not  support one goroutine block read, another goroutine block write concurrnt.
when read block, write goroutine can't write anything, because writer & reader control by 
a sync.RWMutex.

Why?

**Comment by richmonkey** [comment]
revision:3c3145340e676971209507021a435520c2700d92  can support concurrntly read&write.

**Comment by erkie** [comment]
@richmonkey this is an issue that we really would like a pull request for.

**Comment by wangtuanjie** [comment]
https://github.com/googollee/go-engine.io/pull/77

**Comment by erkie** [comment]
@wangtuanjie nice!
